spring:
  main:
    banner-mode: off
  kafka:
    bootstrap-servers: localhost:9092
    producer:
      value-serializer: ru.practicum.ewm.stats.serialization.GeneralAvroSerializer
    consumer:
      value-deserializer: ru.practicum.ewm.serialization.UserActionDeserializer
      group-id: stats.aggregators
      auto-offset-reset: earliest
kafka:
  topics:
    actions: stats.user-actions.v1
    similarity: stats.events-similarity.v1
server:
  port: 0
logging:
  level:
    org.apache.kafka: WARN
