spring:
  main:
    banner-mode: off
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: user-service_route
          uri: lb://user-service
          predicates:
            - Path=/admin/users/**
        - id: requests-service_route
          uri: lb://request-service
          predicates:
            - Path=/users/*/events/*/requests/**, /users/*/requests/**
        - id: like_service_route
          uri: lb://extra-services
          predicates:
            - Path=/events/*/like/**
        - id: event-service_route
          uri: lb://event-service
          predicates:
            - Path=/admin/events/**, /users/*/events/**, /events/**, /categories/**, /admin/categories/**
        - id: extra-services_route
          uri: lb://extra-services
          predicates:
            - Path=/admin/compilations/**, /compilations/**, /users/*/subscriptions/**
server:
  port: 8080
