spring:
  main:
    banner-mode: off
  datasource:
    url: jdbc:postgresql://analyzer-db:5432/analyzer
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: none
    open-in-view: false
  sql:
    init:
      mode: always
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      key-deserializer: org.apache.kafka.common.serialization.LongDeserializer
      auto-offset-reset: earliest
kafka:
  topics:
    actions: stats.user-actions.v1
    similarity: stats.events-similarity.v1
grpc:
  server:
    port: 0
server:
  port: 0
logging:
  level:
    org.apache.kafka: WARN
