spring:
  main:
    banner-mode: off
  kafka:
    bootstrap-servers: localhost:9092
    producer:
      value-serializer: ru.practicum.ewm.stats.serialization.GeneralAvroSerializer
grpc:
  server:
    port: 0
kafka:
  topics:
    actions: stats.user-actions.v1
server:
  port: 0
logging:
  level:
    org.apache.kafka: WARN
