spring:
  main:
    banner-mode: off
  datasource:
    url: jdbc:postgresql://events-db:5432/events
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: none
    open-in-view: false
  sql:
    init:
      mode: always
  cloud:
    openfeign:
      circuitbreaker:
        enabled: true
grpc:
  client:
    collector-service:
      address: 'discovery:///collector-service'
      enable-keep-alive: true
      keep-alive-without-calls: true
      negotiation-type: plaintext
resilience4j:
  circuitbreaker:
    configs:
      default:
        slidingWindowSize: 50
        failureRateThreshold: 50
    instances:
      user-service:
        slidingWindowSize: 10
        waitDurationInOpenState: 10000
        permittedNumberOfCallsInHalfOpenState: 3
        slidingWindowsType: COUNT_BASED
        minimumNumberOfCalls: 5
        automaticTransitionFromOpenToHalfOpenEnabled: true
      ewm-stats-server:
        slidingWindowSize: 10
        waitDurationInOpenState: 10000
        permittedNumberOfCallsInHalfOpenState: 3
        slidingWindowsType: COUNT_BASED
        minimumNumberOfCalls: 5
        automaticTransitionFromOpenToHalfOpenEnabled: true
      request-service:
        slidingWindowSize: 10
        waitDurationInOpenState: 10000
        permittedNumberOfCallsInHalfOpenState: 3
        slidingWindowsType: COUNT_BASED
        minimumNumberOfCalls: 5
        automaticTransitionFromOpenToHalfOpenEnabled: true
ewm:
  timeout:
    admin: PT1H
    user: PT2H
server:
  port: 0
